### ISSUE TITLE
Purpose of your project

### ISSUE THREAD

**Issue by clement-igonet** [ThibaudM/mapbox-gl-js-indoor#2]
Hello Thibaud,
I'm interested in indoor features of mapbox.
Could you share what you did/do by some minimal explanations, an example, or at least a screenshot ?

**Comment by ThibaudM** [comment]
Hello,

I did not have the time to explain what I have done but, to be quick, the goal of this project was to visualize multi-level buildings with a geojson file as input. (it works if you use osmtogeojson tool).
The change list is long because I have also integrated the level object in the camera options through the whole project. You can see the *compare* here: https://github.com/ThibaudM/mapbox-gl-js-indoor/compare/mapbox-v1.7.0...indoor-geojson.

About a sample, I invite you to have a look at this file (https://github.com/ThibaudM/mapbox-gl-js-indoor/blob/indoor-geojson/debug/indoor.html) in **debug** folder.

**Comment by ThibaudM** [comment]
I also did a "public visualisation" here few years ago : http://indoor.thibaud-michel.com/
Three examples:
- https://indoor.thibaud-michel.com/caserne/
- https://indoor.thibaud-michel.com/grand-place/
- https://indoor.thibaud-michel.com/gare-de-lyon/
I should update this one because it uses a very old version of this project with indoor tiles.

**Comment by clement-igonet** [comment]
OK. I'd be interested in reusing your project.
Thx for explanations.

clement@igonet.fr

**Comment by clement-igonet** [comment]
So, I would have been more confortable if your work were a mapbox plugin rather an orphan fork.
I don't see a convenient way to exploit your job done... 🤔

**Comment by ThibaudM** [comment]
You are right; it could be more comfortable with making this project a Mapbox plugin. Therefore, there are two problems to achieve this, as far as I know:
- It is not possible to add the custom expression "inrange" (see https://github.com/ThibaudM/mapbox-gl-js-indoor/blob/indoor-geojson/src/style-spec/expression/definitions/index.js#L571-L589) from outside the main project
- Same problem with the level integration in the camera transform and hash. This second point is not mandatory to make the project works, but it is a rollback.
If you have an idea for a workaround, do not hesitate to tell me.

If you want to exploit this project, you can simply install the package: `@thibaudm/mapbox-gl-js-indoor` from the GitHub registry with npm and use it as the main `mapbox-gl-js` library.

As you understand, this is not a project I am working a lot, but I can try to enhance it if it is possible.

**Comment by clement-igonet** [comment]
Great feedback, thank you.
I'll have a try.
You should try www.indoorequal.org for a minimalist available mapbox exploitation.
Unfortunately, even if I succeeded in generating my own indoor vector tiles for indoorequal front-end, it's a PITA to do it.
Indoor= is not a mapbox fork, but a vue.js project above.
What I like the most in your solution is the fact that a specific geojson can be used directly.
It matches perfectly my need to render just a few buildings on a specific place.
I close the current case. You gave me relevant info.

**Comment by ThibaudM** [comment]
Since new filters introduced in mapboxgl-js 1.10, I am able to create a mapbox plugin with the same approach. I already did a POC, and I am working on a more stable version

**Comment by clement-igonet** [comment]
Good to ear such news.
I'd be fond of trying it !
